# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-06c86996-c125-4cbb-9b60-719fae76b64c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-06c86996-c125-4cbb-9b60-719fae76b64c".device = "/dev/disk/by-uuid/06c86996-c125-4cbb-9b60-719fae76b64c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9CF6-3E7F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/shared" =
    { device = "/dev/disk/by-uuid/2c5e3433-92fd-431d-ba8e-28de7a0351a6";
      fsType = "ext4";
      options = [ "nofail" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
