- name: Clone dwm repository
  ansible.builtin.git:
    repo: "{{ dwm_repository }}"
    dest: "{{ ansible_env.HOME }}/.config/dwm"
    clone: yes
    update: no
    version: "490002a0398cac706419e7c76a426cafe6e9548f"


- name: Install dwm
  become: true
  shell: "cd {{ ansible_env.HOME }}/.config/dwm && make clean install"

- name: Copy .xinitrc file
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
  with_items:
  - .xinitrc
