#!/bin/bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# If branch has the Jira tiquet format, start the commit message with it
# E.g NR-12345 -> NR-12345: bla bla
if [[ -z "$COMMIT_SOURCE" ]]
then
  ref=$(git rev-parse --abbrev-ref HEAD)
  original=$(cat "$COMMIT_MSG_FILE")
  if [[ $ref =~ ^.*((NR|NEWRELIC)-[0-9]+).* ]]
  then
    ticket="${BASH_REMATCH[1]}"
    echo "${ticket}: " > "$COMMIT_MSG_FILE"
  else
    echo "NO_JIRA_TICKET_FOUND_REMOVE_THIS" > "$COMMIT_MSG_FILE"
  fi
  echo "$original" >> "$COMMIT_MSG_FILE"
fi
