wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight: 
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    columns: [35, 35, 35, 35]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    rows: [10, 10, 10, 10, 4]
  refreshInterval: 1
  openFileUtil: "vim"
  mods:
    todoWurg:
      type: todo
      checkedIcon: "X"
      title: "TODO 🚨"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todourg.yml"
      position:
        top: 0
        left: 0
        height: 1
        width: 2
      refreshInterval: 3600
    todoWwarn:
      type: todo
      checkedIcon: "X"
      title: "TODO 🚧"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todowarn.yml"
      position:
        top: 0
        left: 2
        height: 1
        width: 2
      refreshInterval: 3600
    todoWbacklog:
      type: todo
      checkedIcon: "X"
      title: "Backlog 🌈"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todowarn.yml"
      position:
        top: 1
        left: 0
        height: 1
        width: 4
      refreshInterval: 3600
    github:
      title: "⚡️"
      apiKey: ""
      baseURL: ""
      customQueries:
        othersPRs:
          title: "Others Pull Requests"
          filter: "is:open is:pr -author:wtfutil"
      enabled: true
      enableStatus: true
      showStats: false
      position:
        top: 2
        left: 0
        height: 2
        width: 4
      refreshInterval: 5m
      repositories:
        - "newrelic/infrastructure-agent"
        - "newrelic/nrjmx"
        - "newrelic/infra-integrations-sdk"
        - "newrelic/infrastructure-publish-action"
      uploadURL: ""
      username: "rogercoll"

