- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: "{{ dot_repository }}"
    dest: "{{ ansible_env.HOME }}/.config/dotfiles"
    clone: yes
    update: yes


- name: Create .bashrc sym link
  shell: "ln -sf {{ ansible_env.HOME }}/.config/dotfiles/.bashrc {{ ansible_env.HOME }}/.bashrc"

- name: Create .gitconfig sym link
  shell: "ln -sf {{ ansible_env.HOME }}/.config/dotfiles/.gitconfig {{ ansible_env.HOME }}/.gitconfig"

- name: Create .global_gitignore  sym link
  shell: "ln -sf {{ ansible_env.HOME }}/.config/dotfiles/.global_gitignore {{ ansible_env.HOME }}/.global_gitignore"

- name: Create .global_gitignore  sym link
  shell: "ln -sf {{ ansible_env.HOME }}/.config/dotfiles/.global_gitignore {{ ansible_env.HOME }}/.global_gitignore"

- name: Create .nvim sym link
  shell: "ln -sf {{ ansible_env.HOME }}/.config/dotfiles/.config/nvim {{ ansible_env.HOME }}/.config/nvim"

- name: Install vim plugs
  shell: 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
